version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=JiraRush
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres-db:5432/jira
      - spring.profiles.active=prod
    depends_on:
      - postgres-db
    ports:
      - 8080:8080